version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"                    # optional: run on Fridays
      time: "00:00"
      timezone: "Asia/Karachi"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "indirect"

